server {
    listen  80;

    index index.php;
    server_name localhost atiende.localhost atiende.lat ~^(?P<tenant>.+)\.atiende\.localhost$ ~^(?P<tenant>.+)\.atiende\.lat$;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    error_page 404 /index.php;
    root /var/www/atiende;


    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_X_TENANT   $tenant;
    }

    location ~ ^/ticket/(\d+)$ {
        rewrite ^/ticket/(\d+)$ /reportes/exTicket.php?id=$1 last;
    }

    location ~ ^/responder/reclamo/(\d+)/([a-f0-9]+)$ {
        rewrite ^/responder/reclamo/(\d+)/([a-f0-9]+)$ /ws/m/movil.php?id=$1&t=$2 last;
    }

    location ~ ^/responder/consulta/(\d+)/([a-f0-9]+)$ {
        rewrite ^/responder/consulta/(\d+)/([a-f0-9]+)$ /ws/m/movilc.php?id=$1&t=$2 last;
    }

    location ~ ^/responder/listo$ {
        rewrite ^/responder/listo$ /ws/m/finaliza.php last;
    }

    location ~ ^/pedidos/(\d+)$ {
        rewrite ^/pedidos/(\d+)$ /pedidos/index.php?ped=$1 last;
    }

    location ~ ^/pedidos/(\d+)/confirmado$ {
        rewrite ^/pedidos/(\d+)/confirmado$ /pedidos/finaliza.php?ped=$1 last;
    }

    location ~ ^/pedidos/(\d+)/(.+)$ {
        rewrite ^/pedidos/(\d+)/(.+)$ /pedidos/index.php?ped=$1&ved=$2 last;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}